### Teste de conversão de imagem para PDF
POST https://localhost:7001/api/convert/image-to-pdf
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1744570923858.jpg"
Content-Type: image/jpeg

< C:\Users\gatal\Downloads\1744570923858.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW-- 